---
description: Generate an actionable, dependency-ordered tasks.md for the feature based on available design artifacts with enhanced automation and validation.
scripts:
  sh: scripts/bash/check-prerequisites.sh --json
  ps: scripts/powershell/check-prerequisites.ps1 -Json
---

# User Input

```text
$ARGUMENTS
```

You **MUST** consider the user input before proceeding (if not empty).

## Enhanced Features

This tool now supports advanced automation and validation features.

### Automation & Integration

- **Version Control Integration**: Automatically track task status in git branches/commits
- **CI/CD Pipeline Integration**: Validate task completion via automated tests
- **Real-time Codebase Validation**: Cross-reference tasks against existing code
- **Automated Dependency Resolution**: Graph-based analysis for complex relationships

### Expanded Artifact Support

- **Additional Document Types**: Architecture diagrams, wireframes, user flows, API specifications, data flow diagrams
- **External Integrations**: Import from Jira, GitHub Issues, Trello, Linear, Asana, Azure DevOps
- **Custom Artifact Schemas**: Team-defined document types and parsing rules with JSON schema validation
- **Artifact Discovery**: Automatic scanning and classification of project documents
- **Versioned Artifacts**: Support for artifact versioning and change tracking

### Improved Task Quality

- **Configurable Granularity**: Support epics, stories, tasks, subtasks with configurable size limits
- **Smart Task Splitting**: Automatic breakdown based on complexity heuristics (LOC, dependencies, risk factors)
- **Quality Validation**: Built-in checklists for completeness, testability, and acceptance criteria validation
- **Task Estimation**: Automated complexity scoring and time estimation
- **Template-driven Tasks**: Reusable task templates for common patterns

### Enhanced Dependency Management

- **Cross-artifact Dependencies**: Handle relationships between user stories, infrastructure, external systems
- **Dynamic Updates**: Update dependencies as tasks progress with real-time graph recalculation
- **Conflict Resolution**: Detect and resolve circular dependencies with automated suggestions
- **Dependency Visualization**: Interactive dependency graphs with critical path highlighting
- **Impact Analysis**: Assess the impact of changes on dependent tasks and artifacts

### Performance & Scalability

- **Large Codebase Support**: Efficient parsing for projects with thousands of files using parallel processing
- **Incremental Updates**: Only re-analyze changed artifacts with change detection algorithms
- **Caching**: Store intermediate results to speed up regeneration with intelligent cache invalidation
- **Distributed Processing**: Support for processing large artifacts across multiple cores/machines
- **Resource Optimization**: Memory-efficient parsing with streaming for large files

## Outline

### 1. Setup Environment

Run `{SCRIPT}` from repo root and parse FEATURE_DIR and AVAILABLE_DOCS list. All paths must be absolute.
For single quotes in args like "I'm Groot", use escape syntax: e.g 'I'\''m Groot' (or double-quote if possible: "I'm Groot").

### 2. Load Design Documents

Read from FEATURE_DIR:

- **Required**: plan.md (tech stack, libraries, structure), intent.md (user stories with priorities)
- **Optional**: data-model.md (entities), contracts/ (API endpoints), research.md (decisions), quickstart.md (test scenarios)
- **ENHANCED**: architecture.md (system diagrams), wireframes/ (UI mockups), api-specs/ (API documentation)

```text
- **ENHANCED**: Automatically discover and classify additional artifacts in the project (run `scripts/bash/enhanced-artifact-scanner.sh`)
- **ENHANCED**: Validate artifact schemas and versions for consistency
- Note: Not all projects have all documents. Generate tasks based on what's available.
```

### 3. Analyze and Generate Tasks

```text
- Load plan.md and extract tech stack, libraries, project structure
- Load intent.md and extract user stories with their priorities (P1, P2, P3, etc.)
- If data-model.md exists: Extract entities and map to user stories
- If contracts/ exists: Map endpoints to user stories
- If research.md exists: Extract decisions for setup tasks
- Generate tasks organized by user story (see Task Generation Rules below)
- Generate dependency graph showing user story completion order
- Create parallel execution examples per user story
- Validate task completeness (each user story has all needed tasks, independently testable)
- Analyze artifact complexity and suggest task granularity levels (**ENHANCED**)
- Apply smart task splitting based on complexity heuristics (**ENHANCED**)
- Generate quality validation checklists for each task (**ENHANCED**)
- Load existing git repository status and prepare branch tracking (**ENHANCED**)
- Analyze existing codebase for validation and conflict detection (**ENHANCED**)
- Generate automated test integration points for CI/CD pipelines (**ENHANCED**)
```

### 4. Generate Output

Use `.Intended/templates/tasks-template.md` as structure, fill with:

```text
- Correct feature name from plan.md
- Phase 1: Setup tasks (project initialization)
- Phase 2: Foundational tasks (blocking prerequisites for all user stories)
- Phase 3+: One phase per user story (in priority order from intent.md)
- Each phase includes: story goal, independent test criteria, tests (if requested), implementation tasks
- Final Phase: Polish & cross-cutting concerns
- All tasks must follow the strict checklist format (see Task Generation Rules below)
- Clear file paths for each task
- Dependencies section showing story completion order
- Parallel execution examples per story
- Implementation strategy section (MVP first, incremental delivery)
```

### 5. Final Report

Output path to generated tasks.md and summary:

```text
- Total task count
- Task count per user story
- Parallel opportunities identified
- Independent test criteria for each story
- Suggested MVP scope (typically just User Story 1)
- Format validation: Confirm ALL tasks follow the checklist format (checkbox, ID, labels, file paths)
- **ENHANCED**: Git branch status and commit tracking setup
- **ENHANCED**: Codebase validation results and conflict warnings
- **ENHANCED**: CI/CD integration points generated
- **ENHANCED**: Performance metrics and scalability recommendations
```

Context for task generation: {ARGS}

The tasks.md should be immediately executable - each task must be specific enough that an LLM can complete it without
additional context.

## Task Generation Rules

**CRITICAL**: Tasks MUST be organized by user story to enable independent implementation and testing.

**Tests are OPTIONAL**: Only generate test tasks if explicitly requested in the feature specification or if user requests
TDD approach.

### Checklist Format (REQUIRED)

Every task MUST strictly follow this format:

```text
- [ ] [TaskID] [Priority?] [P?] [Story?] Description with file path
```

**Format Components**:

1. **Checkbox**: ALWAYS start with `- [ ]` (markdown checkbox)
2. **Task ID**: Sequential number (T001, T002, T003...) in execution order
3. **Priority**: Task priority level [P1], [P2], [P3] matching user story priority
4. **[P] marker**: Include ONLY if task is parallelizable (different files, no dependencies on incomplete tasks)
5. **[Story] label**: REQUIRED for user story phase tasks only

```text
- Format: [US1], [US2], [US3], etc. (maps to user stories from intent.md)
- Setup phase: NO story label
- Foundational phase: NO story label
- User Story phases: MUST have story label
- Polish phase: NO story label
```

1. **Description**: Clear action with exact file path

**Examples**:

- ✅ CORRECT: `- [ ] T001 [P1] Create project structure per implementation plan`
- ✅ CORRECT: `- [ ] T005 [P1] [P] Implement authentication middleware in src/middleware/auth.py`
- ✅ CORRECT: `- [ ] T012 [P1] [P] [US1] Create User model in src/models/user.py`
- ✅ CORRECT: `- [ ] T014 [P1] [US1] Implement UserService in src/services/user_service.py`
- ❌ WRONG: `- [ ] Create User model` (missing ID, Priority and Story label)
- ❌ WRONG: `T001 [US1] Create model` (missing checkbox)
- ❌ WRONG: `- [ ] [US1] Create User model` (missing Task ID and Priority)
- ❌ WRONG: `- [ ] T001 [US1] Create model` (missing Priority and file path)

### Task Organization

- **From User Stories (intent.md)** - PRIMARY ORGANIZATION:

  ```text
  - Each user story (P1, P2, P3...) gets its own phase
  - Map all related components to their story:
    - Models needed for that story
    - Services needed for that story
    - Endpoints/UI needed for that story
    - If tests requested: Tests specific to that story
  - Mark story dependencies (most stories should be independent)
  ```

- **From Contracts**:

  ```text
  - Map each contract/endpoint → to the user story it serves
  - If tests requested: Each contract → contract test task [P] before implementation in that story's phase
  ```

- **From Data Model**:

  ```text
  - Map each entity to the user story(ies) that need it
  - If entity serves multiple stories: Put in earliest story or Setup phase
  - Relationships → service layer tasks in appropriate story phase
  ```

- **From Setup/Infrastructure**:

  ```text
  - Shared infrastructure → Setup phase (Phase 1)
  - Foundational/blocking tasks → Foundational phase (Phase 2)
  - Story-specific setup → within that story's phase
  ```

### Phase Structure

```text
- **Phase 1**: Setup (project initialization)
- **Phase 2**: Foundational (blocking prerequisites - MUST complete before user stories)
- **Phase 3+**: User Stories in priority order (P1, P2, P3...)
- Within each story: Tests (if requested) → Models → Services → Endpoints → Integration → Documentation
- Each phase should be a complete, independently testable increment
- **Final Phase**: Polish & Cross-Cutting Concerns
```

### Task Quality Standards

```text
- **Specificity**: Tasks must be specific enough for immediate implementation
- **Completeness**: Each task should result in a complete, testable unit
- **Traceability**: Tasks must be traceable back to user stories and requirements
- **Independence**: User stories should remain independently implementable
- **Verifiability**: Each task should have clear success criteria
- **ENHANCED Granularity**: Tasks should fit within configurable size limits (configurable via settings)
- **ENHANCED Estimation**: Each task includes automated complexity scoring and time estimates
- **ENHANCED Validation**: Built-in acceptance criteria checklists automatically generated
```

### Dependency Management

```text
- **Task Dependencies**: Clearly identify and document task dependencies
- **Story Dependencies**: Minimize dependencies between user stories
- **Parallel Opportunities**: Mark tasks that can be executed in parallel
- **Critical Path**: Identify the sequence of tasks that determines project duration
- **ENHANCED Cross-artifact Dependencies**: Track dependencies between different artifact types
- **ENHANCED Dynamic Graph Updates**: Automatically recalculate dependencies as tasks progress
- **ENHANCED Conflict Resolution**: Detect circular dependencies with automated resolution suggestions
- **ENHANCED Impact Analysis**: Assess change impact on dependent tasks and artifacts
```
